sudo: false
language: python

python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"

env:
  - DJANGO=django21
  - DJANGO=django22
  - DJANGO=django30
  - DJANGO=django31
  - DJANGO=djangomaster

matrix:
  exclude:
    - python: "3.5"
      env: DJANGO=django30
    - python: "3.5"
      env: DJANGO=django31
    - python: "3.5"
      env: DJANGO=djangomaster
    - python: "3.8"
      env: DJANGO=django21
  allow_failures:
    - env: DJANGO=djangomaster

before_install:
  - pip install codecov

install:
  - pip install tox

script:
  - TOX_TEST_PASSENV="TRAVIS TRAVIS_JOB_ID TRAVIS_BRANCH" tox -e py${TRAVIS_PYTHON_VERSION//[.]/}-$DJANGO

after_success:
  - codecov
